"""corlinman-server — gRPC entrypoint for the Python AI plane."""

from __future__ import annotations

from corlinman_server.gateway_api import (
    Attachment,
    AttachmentKind,
    ChannelBinding,
    ChatEventStream,
    ChatService,
    ChatServiceBase,
    DoneEvent,
    ErrorEvent,
    InternalChatError,
    InternalChatEvent,
    InternalChatRequest,
    Message,
    Role,
    SharedChatService,
    TokenDeltaEvent,
    ToolCallEvent,
    Usage,
    internal_chat_error_from_corlinman_error,
)
from corlinman_server.main import main
from corlinman_server.scheduler import (
    SCHEDULER_SCHEMA_SQL,
    ActionSpec,
    CronParseError,
    JobAction,
    JobSpec,
    RunRecord,
    Schedule,
    SchedulerConfig,
    SchedulerHandle,
    SchedulerJob,
    SchedulerStore,
    SchedulerStoreConnectError,
    SchedulerStoreError,
    SubprocessOutcome,
    SubprocessOutcomeKind,
    dispatch,
    next_after,
    run_subprocess,
)
from corlinman_server.scheduler import (
    parse as parse_cron,
)
from corlinman_server.scheduler import (
    spawn as spawn_scheduler,
)
from corlinman_server.tenancy import (
    DEFAULT_TENANT_ID,
    SCHEMA_SQL,
    TENANT_SLUG_REGEX_STR,
    AdminDb,
    AdminDbConnectError,
    AdminDbError,
    AdminExistsError,
    AdminRow,
    ApiKeyRow,
    FederationPeer,
    MintedApiKey,
    TenantExistsError,
    TenantId,
    TenantIdEmpty,
    TenantIdError,
    TenantIdInvalidShape,
    TenantPool,
    TenantPoolConnectError,
    TenantPoolCreateDirError,
    TenantPoolError,
    TenantRow,
    default_tenant,
    hash_api_key_token,
    tenant_db_path,
    tenant_root_dir,
)

__all__ = [
    # tenancy
    "DEFAULT_TENANT_ID",
    "SCHEDULER_SCHEMA_SQL",
    "SCHEMA_SQL",
    "TENANT_SLUG_REGEX_STR",
    # scheduler
    "ActionSpec",
    "AdminDb",
    "AdminDbConnectError",
    "AdminDbError",
    "AdminExistsError",
    "AdminRow",
    "ApiKeyRow",
    # gateway_api
    "Attachment",
    "AttachmentKind",
    "ChannelBinding",
    "ChatEventStream",
    "ChatService",
    "ChatServiceBase",
    "CronParseError",
    "DoneEvent",
    "ErrorEvent",
    "FederationPeer",
    "InternalChatError",
    "InternalChatEvent",
    "InternalChatRequest",
    "JobAction",
    "JobSpec",
    "Message",
    "MintedApiKey",
    "Role",
    "RunRecord",
    "Schedule",
    "SchedulerConfig",
    "SchedulerHandle",
    "SchedulerJob",
    "SchedulerStore",
    "SchedulerStoreConnectError",
    "SchedulerStoreError",
    "SharedChatService",
    "SubprocessOutcome",
    "SubprocessOutcomeKind",
    "TenantExistsError",
    "TenantId",
    "TenantIdEmpty",
    "TenantIdError",
    "TenantIdInvalidShape",
    "TenantPool",
    "TenantPoolConnectError",
    "TenantPoolCreateDirError",
    "TenantPoolError",
    "TenantRow",
    "TokenDeltaEvent",
    "ToolCallEvent",
    "Usage",
    "default_tenant",
    "dispatch",
    "hash_api_key_token",
    "internal_chat_error_from_corlinman_error",
    "main",
    "next_after",
    "parse_cron",
    "run_subprocess",
    "spawn_scheduler",
    "tenant_db_path",
    "tenant_root_dir",
]
